import { FaJava } from "react-icons/fa";
import {
  SiJavascript,
  SiTypescript,
  SiSpring,
  SiSpringboot,
  SiMongodb,
  SiJson,
  SiHtml5,
  SiCss3,
  SiChakraui,
  SiBootstrap,
  SiKubernetes,
  SiDocker,
  SiHelm,
  SiSplunk,
  SiPostman,
  SiSwagger,
  SiApachekafka,
  SiGit,
  SiGithub,
  SiJenkins,
  SiJunit5,
  SiReact,
  SiJest,
  SiTestinglibrary,
  SiJira,
  SiFigma,
} from "react-icons/si";
import { AiFillApi } from "react-icons/ai";
import { GrMysql } from "react-icons/gr";
import { RiTestTubeFill } from "react-icons/ri";
import { IconType } from "react-icons";
import { BsKanban } from "react-icons/bs";

export interface Skill {
  name: string;
  label: string;
  icon: IconType;
  categories: string[];
  yearsExperience: string;
  text: string;
}

const skills = [
  {
    name: "java",
    label: "Java",
    icon: FaJava,
    categories: ["Language", "API"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "javascript",
    label: "Javascript",
    icon: SiJavascript,
    categories: ["Language", "Front End"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "typescript",
    label: "Typescript",
    icon: SiTypescript,
    categories: ["Language", "Front End"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "react",
    label: "ReactJS",
    icon: SiReact,
    categories: ["Framework", "Front End"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "html",
    label: "HTML",
    icon: SiHtml5,
    categories: ["Language", "Front End"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "css",
    label: "CSS",
    icon: SiCss3,
    categories: ["Language", "Front End"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "spring",
    label: "Spring",
    icon: SiSpring,
    categories: ["Framework", "API"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "spring-boot",
    label: "Spring Boot",
    icon: SiSpringboot,
    categories: ["Framework"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "mongodb",
    label: "MongoDB",
    icon: SiMongodb,
    categories: ["Database"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "mysql",
    label: "MySQL",
    icon: GrMysql,
    categories: ["Database"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "rest-api",
    label: "RESTful APIs",
    icon: AiFillApi,
    categories: ["API"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "chakraui",
    label: "Chakra UI",
    icon: SiChakraui,
    categories: ["Framework", "Front End"],
    yearsExperience: "< 1 yr",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "bootstrap",
    label: "Bootstrap",
    icon: SiBootstrap,
    categories: ["Framework", "Front End"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "figma",
    label: "Figma",
    icon: SiFigma,
    categories: ["Dev Tools", "Front End"],
    yearsExperience: "< 1 yr",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "json",
    label: "JSON",
    icon: SiJson,
    categories: ["API"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "kubernetes",
    label: "Kubernetes",
    icon: SiKubernetes,
    categories: ["CI/CD", "Containerization"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "docker",
    label: "Docker",
    icon: SiDocker,
    categories: ["CI/CD", "Containerization"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "helm",
    label: "Helm",
    icon: SiHelm,
    categories: ["CI/CD", "Containerization"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "jenkins",
    label: "Jenkins",
    icon: SiJenkins,
    categories: ["CI/CD", "Dev Tools"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "kafka",
    label: "Kafka",
    icon: SiApachekafka,
    categories: ["Streams"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "postman",
    label: "Postman",
    icon: SiPostman,
    categories: ["Dev Tools", "API"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "swagger",
    label: "Swagger",
    icon: SiSwagger,
    categories: ["Dev Tools", "API"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "splunk",
    label: "Splunk",
    icon: SiSplunk,
    categories: ["Dev Tools"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "git",
    label: "Git",
    icon: SiGit,
    categories: ["Dev Tools", "Version Control"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "github",
    label: "GitHub",
    icon: SiGithub,
    categories: ["Dev Tools", "Version Control"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "junit5",
    label: "JUnit 5",
    icon: SiJunit5,
    categories: ["Testing", "Framework"],
    yearsExperience: "3 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "mockito",
    label: "Mockito",
    icon: RiTestTubeFill,
    categories: ["Testing", "Framework"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "jest",
    label: "Jest",
    icon: SiJest,
    categories: ["Testing", "Framework"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "react-testing-library",
    label: "React Testing Library",
    icon: SiTestinglibrary,
    categories: ["Testing", "Framework"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "agile",
    label: "Agile",
    icon: BsKanban,
    categories: ["Methodology"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
  {
    name: "jira",
    label: "Jira",
    icon: SiJira,
    categories: ["Methodology", "Dev Tools"],
    yearsExperience: "2 yrs",
    text: "This is some sample text for a card to see what it looks like.  I want to describe my experience with each of these technologies so recruiters can clearly see how I use them.",
  },
];

export const skillCategories = [
  "All Skills",
  "Language",
  "Front End",
  "Database",
  "API",
  "Framework",
  "CI/CD",
  "Containerization",
  "Dev Tools",
  "Testing",
  "Streams",
  "Methodology",
  "Version Control",
  "IDE",
];

const useSkills = () => skills;

export default useSkills;
